feat: セッション用DB作成
CA22-game-creators/cookingbomb-apiserver pull request #34
Opened 2021-05-12 03:08 UTC by karamaru-alpha

## Issues
#33 
## About
セッション用DB作成
## Background
認証のためにセッショントークン・有効期限を管理したいため
## Details
- ユーザーテーブルに紐づくセッションテーブルを作成
-  外部キー制約で紐づくユーザーが削除されたらセッションレコードも削除される
- `session_token`は暗号化されていないUUIDなので`cha(36)`で、`user_id`はULIDなので`char(26)`
※uuidは予測困難性に優れているためトークンに採用し、ulidはソートできるなどの利点からUserIDに採用
## Preview
```
$ make migrate
$  show full columns from sessions; (in mysql)
```
<img width="1118" alt="スクリーンショット 2021-05-12 12 02 12" src="https://user-images.githubusercontent.com/38310693/117912142-e441bd80-b319-11eb-9bce-ddb736ff8d9d.png">

2021-05-12 03:19 UTC, moritaoy commented
もし、`user_id`で作るのなら、Userテーブルも統一した方が良い気がするけどどうだろう？
今ならまだスキーマ修正被害小さそう

2021-05-12 03:20 UTC, moritaoy commented
あれ、なんか`id`にする理由があった気がするな？見返します

2021-05-12 03:22 UTC, moritaoy requested changes
これ、session_tokenにINDEX張らないとやばいと思う

2021-05-13 09:40 UTC, karamaru-alpha commented
> あれ、なんかidにする理由があった気がするな？見返します

Sessionテーブルの`user_id`は、Userテーブルのidってカラムに紐づく外部キーだよ！って意味だから、UserテーブルのPRYMARY_KRYは`id`のままでいいと思ってる！

もし「紐づく先と同名にする」ってルールにしちゃうと、子テーブルから紐づくカラムが増えるたびにrenameしないといけなくなるし、なによりテーブルとカラムで意味が重複しちゃうから👀

2021-05-13 09:42 UTC, moritaoy commented
> Sessionテーブルのuser_idは、Userテーブルのidってカラムに紐づく外部キーだよ！って意味
な～るほど！そういう命名方法があるのか！
言われてみると合点がいくから良さそう！

2021-05-13 09:43 UTC, karamaru-alpha commented
[公式の外部キー説明の例](onsole.cloud.google.com/projectselector2/home/dashboard?folder=true&organizationId=true&supportedpurview=project)もその命名だから参考にでmm

2021-05-13 09:49 UTC, karamaru-alpha commented
> これ、session_tokenにINDEX張らないとやばいと思う

あーたしかにそうだね。
User.AuthTokenは暗号化されているからUserIDで取得->照合だけど、Session.SessionTokenはtokenが平文で一意だからSessionTokenでfindByできた時点で照合完了なのか！

修正するね！

2021-05-13 10:00 UTC, moritaoy commented
@karamaru-alpha あー後追記！
session_tokenには、一応UNIQUE制約張っておいた方が良いかも！入れとく分には損が無し！
(あとリンクまだ壊れております)

2021-05-13 10:02 UTC, karamaru-alpha commented
> session_tokenには、一応UNIQUE制約張っておいた方が良い

間違いない！！！
教えてくれて助かるううう

（リンク直しましたごめんなさいmm

2021-05-13 14:36 UTC, karamaru-alpha commented on infrastructure/mysql/schemas/.skeema
> +generator=skeema:1.5.1-community
いつかここの差分が出ないようにしたい

2021-05-14 00:08 UTC, moritaoy approved these changes
よさそうLGTM！
一応だけど、この状態だとsessionは1本しか張れないけど、問題ないよね！
(むしろゲームなので、複数セッションは嬉しくないし）

2021-05-14 10:14 UTC, karamaru-alpha commented
> sessionは1本しか張れないけど、問題ない

今のところは大丈夫そう・・？
セッショントークンを更新して、そのトークンの返却を失敗した時はauthTokenで再度refreshできるようにすれば！

2021-05-14 10:14 UTC, merged